steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Update staging server
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      set -x && \
      gcloud compute ssh --zone "asia-south1-c" "ecotag"  --project "gentle-nuance-380510" --command='/bin/sh /home/jayantsogikar/getCode.sh'
  
options:
  logging: CLOUD_LOGGING_ONLY